### ISSUE TITLE
Can't retrieve marked up article

### ISSUE THREAD

**Issue by mbanerjeepalmer** [Commentative/commentative#33]
New commenting fixes from @reubengt seem to work well. But the generated URL then doesn't work. For example:

```
Cannot GET /847c127d-ee15-428a-b507-32cf7a1b596a
```

Reproduce by:
1. Pasting a link
2. Submitting a comment
3. Copying the new URL
4. Pasting the new URL into a new browser window, or refreshing the page.

**Comment by reubengt** [comment]
yep known issue, need to update backend for this. I was trying to fix as much as possible on frontend first haha

**Comment by reubengt** [comment]
#37 fixes this

**Comment by mbanerjeepalmer** [comment]
Yep, works well: http://commentative.herokuapp.com/09cdffed-f4b2-455f-a90b-e145f47bbc68
